name: 'mandatory-reviews'
on: # rebuild any PRs and main branch changes
  pull_request_review:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ankeetmaini/mandatory-reviews@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          usernames: varshasaha
